@isTest
private class TestRestrictContactByName {
    @isTest static void testRestrictCOntactByNameTrigger(){
        Contact con = new Contact(LastName = 'INVALIDNAME');
        Test.startTest();
        Database.SaveResult result = Database.insert(con,false);
        Test.stopTest();
        System.assert(!result.isSuccess());
        System.assert(result.getErrors().size() > 0);
        
    }
}